line-length = 88
target-version = 'py39'
fix = true

[lint]
select = ['E', 'W', 'F', 'C', 'B', 'I', 'UP']
ignore = ['E501']
exclude = ['notebooks/']

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true

[format]
quote-style = 'single'
preview = true
skip-magic-trailing-comma = false