[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "aciunaef-asdf#iuölknacdaisdfäaeinc,1asdf3iankvcxla"
client_id = "1054531830213-22pq6u0aojk3482bm5sk1sltbc1jbf6v.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

[authz]
allowed_emails = [
  "xaver.heuser@gmail.com",
  "developeracc26@gmail.com"
]